Add option for disabled tabs
scottaohara/accessible_tabs pull request #17
Opened 2019-07-18 08:13 UTC by polarbirke

Create a disabled tab if `data-tabs-disabled` is present on the original
panel. To create parity with the visual output, the disabled tabs can be
reached via keyboard navigation and assistive technology (AT).

Disabled tabs should be styled to look disabled, i.e. by decreasing their
`opacity` to `0.5`. AT should then read out "tab, dimmed" or even
"tab, disabled" if they can interpret the `aria-disabled` attribute.

Disabled tabs do not activate their respective panels.

2019-08-06 14:58 UTC, scottaohara requested changes
hey @polarbirke, 

could you please create a test to review these changes?  I tried pulling down from your branch but adding the attribute didn't seem to do anything when attempting to test for this.

Also, i'm unsure as to why a disabled panel would need a class?  if the tab cannot be selected to activate it, then it should not be able to be rendered.

Thanks

2019-08-07 10:35 UTC, polarbirke commented
Hi @scottaohara,

thanks for the feedback! I have refactored the code and added a test case. Please let me know if I missed anything else!

2019-09-26 14:22 UTC, polarbirke commented
Hi @scottaohara,

do you need anything else from me? Or do you question the merit of this feature in general? Would be great to move forward (mainly so I can close a ticket in our issue tracker 😅), but if you're busy there's no need to rush things.

2019-10-04 00:25 UTC, scottaohara commented
hi @polarbirke 
apologies this completely fell off my radar.  I'll give this a look asap.

2019-10-08 08:50 UTC, polarbirke commented
> hi @polarbirke
> apologies this completely fell off my radar. I'll give this a look asap.

Hey @scottaohara, no worries. Happy to answer questions or debate the rationale behind it all any time. ☕️

2019-10-08 18:02 UTC, scottaohara commented
So, some additional things need to be updated here.

Being that the `tab` is only receiving `aria-disabled`, nothing actually is disabled about it.  I can still navigate to it with arrow keys, activate it with mouse or keyboard.  I shouldn't be able to do any of that.

The tab must not be able to receive keyboard focus, nor allow for mouse click / tab activation.

2019-10-09 06:40 UTC, polarbirke commented
Ah, interesting. Thank you for looking into this! In my reasoning I (foolishly?) thought it would be beneficial if the `tab` was navigable but _announced_ as disabled. I hoped this might lead to better parity for sighted/non-sighted users especially. My client uses a tabbed interface to disclose and present different kinds of data about a resource and in their domain a disabled tab is a way of showing "usually there is this kind of data for this kind of resource, but it's not published yet". What I have tried to build is a variant that tries to mimic the case where a sighted user can infer this information from the visual style, whereas users of AT can have it announced to them. Does that make any sense?

In case you at least partly agree, is there a way to have the `tab` label read out as "Tab, some info, disabled" without it gaining focus/being navigable?

In case you think my reasoning is flawed, I'll be quite happy to follow your judgment and disable it completely.

Thanks again!

2019-10-09 12:48 UTC, scottaohara commented
I wouldn't describe your thinking as foolish, so please don't say that :), but it was flawed in this instance. 

screen reader users could very well still navigate to a disabled tab element if they are navigating via the virtual cursor.  It'd be unexpected to navigate to elements that appear disabled, and completely unexpected for the disabled element to be functional in any way.

Even for screen readers that go into forms/application mode when entering a tablist, typically the number of tabs in the list will be announced.  So if one were to realize they only had access to 3 out of 5 tabs, they could disable forms mode and then navigate via virtual cursor to the other disabled tabs, per my description above.

2019-10-16 13:00 UTC, polarbirke commented
Hi @scottaohara,

thank you for the update! I was not aware that the virtual cursor has this ability. 👍🏻 I agree that unexpected behaviour should be avoided and have updated the code with your recommendations:

- `click` and keyboard event listeners are only attached to non-disabled Tabs/Panels
- I have implemented a `preventFocus`-method to _really_ prevent disabled Tabs from gaining focus (I hope this doesn't conflict with the virtual cursor)

I have left the structural attributes (`role`, `aria-controls`, `aria-selected`) to be set even though the tab is disabled (and the panel is still rendered, albeit always `hidden`) – does this make sense because it still is a `tab` (even if disabled) that `controls` a panel (in theory)? Or is it unnecessary noise?

2019-10-16 14:00 UTC, scottaohara commented
hey @polarbirke, i appreciate you taking the time to give this another shot.

I'll give this a proper review as soon as i can.

2019-11-28 07:54 UTC, polarbirke commented
Hi @scottaohara, just pinging to remind you of this PR. Still no hurry, though.

2020-01-29 08:58 UTC, polarbirke commented
Hey @scottaohara – happy new year to you! I'm about to use your tab widget in another project and remembered this open PR; do you think we can have another look at the disabled option? ☺️

2020-01-29 13:55 UTC, scottaohara commented
Thanks for sticking with me @polarbirke 

Just gave it a look over and it seems in good shape!  Thank you.

One additional request (if you have time) is might you provide an update to an example to demonstrate how someone could re-enable a disabled tab?

If you don't have time, don't worry about it and I'll merge from here.  If you do have time to put that together, then please add it to this PR.

Thanks again

2020-01-29 13:56 UTC, scottaohara approved these changes

2020-02-18 11:22 UTC, polarbirke commented
Hej Scott, 

I'm not entirely sure what you mean here: 

> One additional request (if you have time) is might you provide an update to the example for disabled tabs to demonstrate how someone could re-enable a disabled tab? (e.g. press a button to make the tab enabled)

- Would you like to illustrate the difference between enabled and disabled tabs in the demo by toggling the setting on the same tab? I don't yet understand the advantage over having two enabled and one disabled tabs, but I could of course add that. 👍

- Do you think that users should be able to toggle the setting on real-life websites? The decision whether a tab is disabled has always been an editorial concern in my mind and not something that is customizable in user land. Am I missing something? 😳

As always, thank you for your feedback and time!

2020-02-18 12:22 UTC, scottaohara commented
Sort of what you describe in bullet two, but not quite.

The situation I'm thinking of / have seen happen is using a Tab widget in a multi-step process, where a user completes a task in the exposed tab panel or panels, and then by completion of that task the next Tab becomes enabled.

Rather than simulating that exactly, I was thinking "just put a button within one of the tab panels that would enable the disabled tab"

2020-02-18 13:36 UTC, polarbirke commented
Ah, fabulous! That sounds absolutely reasonable. I will mock that functionality with corresponding comments – thanks for the insight!

I should have time to work on it this week. 👨‍💻

2020-02-20 15:14 UTC, polarbirke commented
Hey Scott,

my colleague Lukas gave me a leg up and added the demo – is this what you envisioned?

2020-02-20 15:24 UTC, scottaohara commented
thanks!  will give it a review this weekend.

2020-08-03 12:16 UTC, polarbirke commented
Hi Scott,

any thoughts on this PR? I just saw we missed its first anniversary 😁 The last update was the addition of a demo by my colleague.

All the best to you and yours!

2021-12-15 13:53 UTC, scottaohara commented
@polarbirke, thank you again for this and sorry it took forever and a day for me to finally give this a proper review.

better late than never i suppose?

2021-12-15 13:53 UTC, merged

2021-12-15 14:00 UTC, polarbirke commented
No worries, I see and appreciate the work you do everywhere else. 👍 

Thanks for the merge!